/* Automatically generated by './build/bin/build-entry.js' */
import 'babel-polyfill'
import P8Button from '../packages/button/index.js';
import P8Card from '../packages/card/index.js';
import P8Dialog from '../packages/dialog/index.js';
import P8ListLayout from '../packages/list-layout/index.js';
import P8NormalLayout from '../packages/normal-layout/index.js';
import P8Tree from '../packages/tree/index.js';
import P8Table from '../packages/table/index.js';
import P8Drawer from '../packages/drawer/index.js';
import P8Form from '../packages/form/index.js';
import P8Upload from '../packages/upload/index.js';
import P8FileView from '../packages/fileView/index.js';
import P8Search from '../packages/search/index.js';
import P8InfiniteScroll from '../packages/infiniteScroll/index.js';
import P8StatusIcon from '../packages/statusIcon/index.js';
import P8Tabs from '../packages/tabs/index.js';
import P8EditTable from '../packages/editTable/index.js';
import P8FormParser from '../packages/formApplication/index.js';
import P8FormGenerator from '../packages/formGenerator/index.js';

const components = [
  P8Button,
  P8Card,
  P8Dialog,
  P8ListLayout,
  P8NormalLayout,
  P8Tree,
  P8Table,
  P8Drawer,
  P8Form,
  P8Upload,
  P8FileView,
  P8Search,
  P8InfiniteScroll,
  P8StatusIcon,
  P8Tabs,
  P8EditTable,
  P8FormParser,
  P8FormGenerator
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.2',
  install,
  P8Button,
  P8Card,
  P8Dialog,
  P8ListLayout,
  P8NormalLayout,
  P8Tree,
  P8Table,
  P8Drawer,
  P8Form,
  P8Upload,
  P8FileView,
  P8Search,
  P8InfiniteScroll,
  P8StatusIcon,
  P8Tabs,
  P8EditTable,
  P8FormParser,
  P8FormGenerator
};
